live_config_reload = true

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
startup_mode = "Fullscreen"
decorations = "None"
dynamic_padding = false
opacity = 0.80

[window.padding]
x = 4
y = 0

[cursor.style]
shape = "Underline"
blinking = "Always"
